In [1]:
'''NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.
Part 1: Dataset Creation'''
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)


Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [2]:
#Part 2 : Basic Array Understanding
# Q1 : Array Dimensions

num_dimensions = sales_data.ndim
print("Number of dimensions : ",num_dimensions)

shape = sales_data.shape
print("Shape of the array : ",shape)

total = sales_data.size
print("Total number of elements : ",total)

data_type = sales_data.dtype
print("Data type of the array : ",data_type)

memory = sales_data.nbytes
print("Memory occupied by the array : ",memory)





Number of dimensions :  2
Shape of the array :  (5, 6)
Total number of elements :  30
Data type of the array :  int64
Memory occupied by the array :  240


In [ ]:
#Q2 : Store and Category Count

store = len(stores)
print("Number of stores : ",store)

category = len(categories)
print("Number of categories : ",category)

Number of stores :  5
Number of categories :  6


In [ ]:
#Q3 : Sales Data Type COnversion

sales_float32= sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("Sales Data (float32):")
print(sales_float32)

print("\nSales Data (float64):")
print(sales_float64)

Sales Data (float32):
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]

Sales Data (float64):
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


In [ ]:
#Q4 :  Bengaluru Store Analysis

bengaluru_sales = sales_data[0]
print("Bengaluru Store Sales:")
print(bengaluru_sales)

Bengaluru Store Sales:
[850000 420000 310000 275000 190000 225000]


In [ ]:
#Q5 : Mumbai Cost Analysis

mumbai_cost = cost_data[3]
print("Mumbai Cost Data: ")
print(mumbai_cost)

Mumbai Cost Data: 
[790000 390000 265000 250000 165000 205000]


In [ ]:
#Q6 : Electonics Sales Across Stores

electronics_sales = sales_data[:,0]
print("Electronics Sales Across Stores:")
print(electronics_sales)

Electronics Sales Across Stores:
[ 850000  780000  920000 1050000  690000]


In [ ]:
#Q7 : Clothing Cost Across Stores

clothing_cost = cost_data[:,2]
print("Clothing Cost Across Stores:")
print(clothing_cost)

Clothing Cost Across Stores:
[220000 210000 245000 265000 205000]


In [5]:
#Q8 : Hydreabad Furniture Performance

hyd_furniture = sales_data[1,3]
print("Hydreabad Furniture Performance:")
print(hyd_furniture)

Hydreabad Furniture Performance:
310000


In [6]:
#Q9 : Chennai Category Range

chennai_category_range = np.max(sales_data[2]) - np.min(sales_data[2])
print("Chennai Category Range:")
print(chennai_category_range)

Chennai Category Range:
735000


In [ ]:
#Q10 : Selected Store Analysis

selected_sales = sales_data[[0, 2, 4]][:, [0, 2, 4]]
print("Selected Sales Data:")
print(selected_sales)


Selected Sales Data:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [7]:
#Part 4 : Sales Aggregation
#Q11 : Company Wide Sales

total_sales = np.sum(sales_data)
print("Total Sales :",total_sales)

Total Sales : 11675000


In [8]:
#Q 12 : Store Wise Sales

blr_sales = np.sum(sales_data[0])
hyd_sales = np.sum(sales_data[1])
chennai_sales = np.sum(sales_data[2])
mumbai_sales = np.sum(sales_data[3])
pune_sales = np.sum(sales_data[4])

print("Store-wise Sales:")
print("Bengaluru:", blr_sales)
print("Hyderabad:", hyd_sales)
print("Chennai:", chennai_sales)
print("Mumbai:", mumbai_sales)
print("Pune:", pune_sales)


Store-wise Sales:
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


In [ ]:
#Q13 : Category Wise Sales

electronics_sales = np.sum(sales_data[:,0])
groceries_sales = np.sum(sales_data[:,1])
clothing_sales = np.sum(sales_data[:,2])
furniture_sales = np.sum(sales_data[:,3])
beauty_sales = np.sum(sales_data[:,4])
sports_sales = np.sum(sales_data[:,5])

print("Category-wise Sales:")
print("Electronics:", electronics_sales)
print("Groceries:", groceries_sales)
print("Clothing:", clothing_sales)
print("Furniture:", furniture_sales)
print("Beauty:", beauty_sales)
print("Sports:", sports_sales)

Category-wise Sales:
Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


In [ ]:
#Q14 : Average Sales Per Store

blr_average = np.mean(sales_data[0])
hyd_average = np.mean(sales_data[1])
chennai_average = np.mean(sales_data[2])
mumbai_average = np.mean(sales_data[3])
pune_average = np.mean(sales_data[4])
print("Average Sales Per Store:")
print("Bengaluru:", blr_average)
print("Hyderabad:", hyd_average)
print("Chennai:", chennai_average)
print("Mumbai:", mumbai_average)
print("Pune:", pune_average)

Average Sales Per Store:
Bengaluru: 378333.3333333333
Hyderabad: 382500.0
Chennai: 385000.0
Mumbai: 470000.0
Pune: 330000.0


In [ ]:
#Q15 : Average Sales Per Category

electronics_average = np.mean(sales_data[:,0])
groceries_average = np.mean(sales_data[:,1])
clothing_average = np.mean(sales_data[:,2])
furniture_average = np.mean(sales_data[:,3])
beauty_average = np.mean(sales_data[:,4])
sports_average = np.mean(sales_data[:,5])
print("Average Sales Per Category:")
print("Electronics:", electronics_average)
print("Groceries:", groceries_average)
print("Clothing:", clothing_average)
print("Furniture:", furniture_average)
print("Beauty:", beauty_average)
print("Sports:", sports_average)

Average Sales Per Category:
Electronics: 858000.0
Groceries: 437000.0
Clothing: 320000.0
Furniture: 283000.0
Beauty: 202000.0
Sports: 235000.0


In [ ]:
#Q16 : Highest Selling Store

highest_selling_store = np.argmax(np.sum(sales_data, axis=1))
sales = np.sum(sales_data, axis=1)
print("Highest Selling Store:", stores[highest_selling_store])
print("Total Sales:", sales[highest_selling_store])

Highest Selling Store: Mumbai
Total Sales: 2820000


In [ ]:
#Q17 : Lowest Selling Store

lowest_selling_store = np.argmin(np.sum(sales_data, axis=1))
sales = np.sum(sales_data, axis=1)
print("Lowest Selling Store:", stores[lowest_selling_store])
print("Total Sales:", sales[lowest_selling_store])

Lowest Selling Store: Pune
Total Sales: 1980000


In [9]:
#Q18 : Highest Selling Category

highest_selling_category = np.argmax(np.sum(sales_data, axis=0))
sales = np.sum(sales_data, axis=0)
print("Highest Selling Category:", categories[highest_selling_category])
print("Total Sales:", sales[highest_selling_category])


Highest Selling Category: Electronics
Total Sales: 4290000


In [ ]:
#Q19: Lowest Selling Category

lowest_selling_category = np.argmin(np.sum(sales_data, axis=0))
sales = np.sum(sales_data, axis=0)
print("Lowest Selling Category:", categories[lowest_selling_category])
print("Total Sales:", sales[lowest_selling_category])

Lowest Selling Category: Beauty
Total Sales: 1010000


In [10]:
#Part 5 : Cost Analysis
#Q20 : Total Company Cost

total_cost = np.sum(cost_data)
print("Total Company Cost:", total_cost)

Total Company Cost: 8600000


In [11]:
#Q21 : Store Wise Cost

blr_cost = np.sum(cost_data[0])
hyd_cost = np.sum(cost_data[1])
chennai_cost = np.sum(cost_data[2])
mumbai_cost = np.sum(cost_data[3])
pune_cost = np.sum(cost_data[4])

print("Store-wise Cost:")
print("Bengaluru:", blr_cost)
print("Hyderabad:", hyd_cost)
print("Chennai:", chennai_cost)
print("Mumbai:", mumbai_cost)
print("Pune:", pune_cost)

Store-wise Cost:
Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


In [ ]:
#Q22 : Category Wise Cost

electronics_cost = np.sum(cost_data[:,0])
groceries_cost = np.sum(cost_data[:,1])
clothing_cost = np.sum(cost_data[:,2])
furniture_cost = np.sum(cost_data[:,3])
beauty_cost = np.sum(cost_data[:,4])
sports_cost = np.sum(cost_data[:,5])
print("Category-wise Cost:")
print("Electronics:", electronics_cost)
print("Groceries:", groceries_cost)
print("Clothing:", clothing_cost)
print("Furniture:", furniture_cost)
print("Beauty:", beauty_cost)
print("Sports:", sports_cost)

Category-wise Cost:
Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


In [12]:
#Q23 : Most Expenisve Store

most_expensive_store = np.argmax(np.sum(cost_data, axis=1))
cost = np.sum(cost_data, axis=1)
print("Most Expensive Store:", stores[most_expensive_store])
print("Total Cost:", cost[most_expensive_store])

Most Expensive Store: Mumbai
Total Cost: 2065000


In [ ]:
#Q24 : Lowest Cost Store

lowest_cost_store = np.argmin(np.sum(cost_data, axis=1))
cost = np.sum(cost_data, axis=1)
print("Lowest Cost Store:", stores[lowest_cost_store])
print("Total Cost:", cost[lowest_cost_store])

Lowest Cost Store: Pune
Total Cost: 1475000


In [13]:
#Q25 : Most Expenisve Product Category

most_expensive_category = np.argmax(np.sum(cost_data, axis=0))
cost = np.sum(cost_data, axis=0)
print("Most Expensive Product Category:", categories[most_expensive_category])
print("Total Cost:", cost[most_expensive_category])

Most Expensive Product Category: Electronics
Total Cost: 3250000


In [15]:
#Part 6 : Profit Analysis Using Two Arrays
#Q26 : Profit MAtrix

profit_data = sales_data - cost_data

print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [16]:
#q27 : Store Wise Profit

blr_profit = np.sum(profit_data[0])
hyd_profit = np.sum(profit_data[1])
chennai_profit = np.sum(profit_data[2])
mumbai_profit = np.sum(profit_data[3])
pune_profit = np.sum(profit_data[4])

print("Store-wise Profit:")
print("Bengaluru:", blr_profit)
print("Hyderabad:", hyd_profit)
print("Chennai:", chennai_profit)
print("Mumbai:", mumbai_profit)
print("Pune:", pune_profit)

Store-wise Profit:
Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


In [ ]:
#Q28 : Category Wise Profit

electonics_profit = np.sum(profit_data[:,0])
groceries_profit = np.sum(profit_data[:,1])
clothing_profit = np.sum(profit_data[:,2])
furniture_profit = np.sum(profit_data[:,3])
beauty_profit = np.sum(profit_data[:,4])
sports_profit = np.sum(profit_data[:,5])

print("Category-wise Profit:")
print("Electronics:", electonics_profit)
print("Groceries:", groceries_profit)
print("Clothing:", clothing_profit)
print("Furniture:", furniture_profit)
print("Beauty:", beauty_profit)
print("Sports:", sports_profit)

Category-wise Profit:
Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


In [ ]:
#29 : Most Profitable Store

most_profitable_store = np.argmax(np.sum(profit_data, axis=1))
sales = np.sum(sales_data, axis=1)
cost = np.sum(cost_data, axis=1)
profit = np.sum(profit_data, axis=1)
print("Most Profitable Store:", stores[most_profitable_store])
print("Total Sales:", sales[most_profitable_store])
print("Total Cost:", cost[most_profitable_store])
print("Total Profit:", profit[most_profitable_store])

Most Profitable Store: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


In [17]:
#30 : Least Profitable Store

least_profitable_store = np.argmin(np.sum(profit_data, axis=1))
sales = np.sum(sales_data, axis=1)
cost = np.sum(cost_data, axis=1)
profit = np.sum(profit_data, axis=1)
print("Least Profitable Store:", stores[least_profitable_store])
print("Total Sales:", sales[least_profitable_store])
print("Total Cost:", cost[least_profitable_store])
print("Total Profit:", profit[least_profitable_store])

Least Profitable Store: Pune
Total Sales: 1980000
Total Cost: 1475000
Total Profit: 505000


In [ ]:
#Q31 : Most Profitable Category

most_profitable_category = np.argmax(np.sum(profit_data, axis=0))
sales = np.sum(sales_data, axis=0)
cost = np.sum(cost_data, axis=0)
profit = np.sum(profit_data, axis=0)
print("Most Profitable Category:", categories[most_profitable_category])
print("Total Sales:", sales[most_profitable_category])
print("Total Cost:", cost[most_profitable_category])
print("Total Profit:", profit[most_profitable_category])


Most Profitable Category: Electronics
Total Sales: 4290000
Total Cost: 3250000
Total Profit: 1040000


In [ ]:
#Q32 : Least Profitable Category

least_profitable_category = np.argmin(np.sum(profit_data, axis=0))
sales = np.sum(sales_data, axis=0)
cost = np.sum(cost_data, axis=0)
profit = np.sum(profit_data, axis=0)
print("Least Profitable Category:", categories[least_profitable_category])
print("Total Sales:", sales[least_profitable_category])
print("Total Cost:", cost[least_profitable_category])
print("Total Profit:", profit[least_profitable_category])

Least Profitable Category: Sports
Total Sales: 1175000
Total Cost: 835000
Total Profit: 340000


In [ ]:
#Q33 : Maximum Individual Profit

profit_data = sales_data - cost_data
max_profit = np.max(profit_data)
row, col = np.unravel_index(np.argmax(profit_data), profit_data.shape)

print("Maximum Individual Profit")
print("Profit Amount :", max_profit)
print("Store         :", stores[row])
print("Category      :", categories[col])


Maximum Individual Profit
Profit Amount : 260000
Store         : Mumbai
Category      : Electronics


In [ ]:
#Q34 : Minimum Individual profit
profit_data = sales_data - cost_data
min_profit = np.min(profit_data)
row, col = np.unravel_index(np.argmin(profit_data), profit_data.shape)

print("Minimum Individual Profit")
print("Profit Amount :", min_profit)
print("Store         :", stores[row])
print("Category      :", categories[col])

Minimum Individual Profit
Profit Amount : 55000
Store         : Pune
Category      : Furniture


In [73]:
#Part 7 : Profit Margin Analysis
#Q35 : Profit Margin Matrix

profit_data = sales_data - cost_data
profit_margin = np.round((profit_data / sales_data) * 100, 2)
print("Profit Margin Matrix (%):")
print(np.column_stack((stores, profit_margin)))

Profit Margin Matrix (%):
[['Bengaluru' '24.71' '25.0' '29.03' '25.45' '34.21' '28.89']
 ['Hyderabad' '24.36' '23.91' '28.81' '27.42' '33.33' '29.17']
 ['Chennai' '23.91' '24.36' '27.94' '25.0' '35.14' '27.91']
 ['Mumbai' '24.76' '23.53' '29.33' '27.54' '34.0' '29.31']
 ['Pune' '23.19' '23.46' '26.79' '24.44' '34.29' '29.27']]


In [ ]:
#Q36 : Store Wise PRofit Margin



In [ ]:
#Q37 : Category wise Profit margin


In [ ]:
#Q38 : Best store by profit margin

In [ ]:
#Q39 : Best Category by profit margin

In [ ]:
#40 : Low MArgin Transcation


In [19]:
#PArt 8 : Boolean Filering
#41 : High Sales Vaules
high_sales = sales_data[sales_data > 500000]
print("High Sales Values:")
print(high_sales)

High Sales Values:
[ 850000  780000  920000 1050000  510000  690000]


In [20]:
#Q42 : Low Sals Values
low_sales = sales_data[sales_data < 200000]

print("Low Sales Values:")
print(low_sales)

Low Sales Values:
[190000 185000 175000]


In [ ]:
#Q43 : High Profit Vaules

high_profit = profit_data[profit_data > 150000]
print("High Profit Values:")
print(high_profit)

High Profit Values:
[210000 190000 220000 260000 160000]


In [21]:
#Q44 : Moderate Sales Range

moderate_sales = sales_data[np.logical_and(sales_data >= 250000,sales_data <= 500000)]
print("Moderate Sales Values:")
print(moderate_sales)

Moderate Sales Values:
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [ ]:
#Q45 : Premium Performance

profit_data = sales_data - cost_data
premium = np.logical_and(sales_data > 500000, profit_data > 150000)
row, col = np.where(premium)

print("Store:", stores[row])
print("Category:", categories[col])
print("Sales:", sales_data[row, col])
print("Profit:", profit_data[row, col])

Store: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
Category: ['Electronics' 'Electronics' 'Electronics' 'Electronics' 'Electronics']
Sales: [ 850000  780000  920000 1050000  690000]
Profit: [210000 190000 220000 260000 160000]


In [ ]:
#Q46 : Underpreforming
profit_data = sales_data - cost_data
profit_margin = np.round((profit_data / sales_data) * 100, 2)
underperforming = np.logical_and(sales_data < 250000, profit_margin < 25)
row, col = np.where(underperforming)

print("Store:", stores[row])
print("Category:", categories[col])
print("Sales:", sales_data[row, col])
print("Profit:", profit_data[row, col])

Store: ['Pune']
Category: ['Furniture']
Sales: [225000]
Profit: [55000]


In [ ]:
#Q47 : Category Performace Classification
performance = np.where(sales_data >= 500000,"High",np.where(sales_data >= 250000,"Medium","Low"))

print(performance)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


In [22]:
#Part 9 : Target Based Analysis
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [23]:
#Question 48 : Target Compariosn
target_comparison = sales_data >= sales_targets

print(target_comparison)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [ ]:
#Q49 : Target Achivement MAtrix
target_achievement = sales_data >= sales_targets
print("Target Achievement Matrix:")
print(target_achievement)

Target Achievement Matrix:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [ ]:
#Q50 : Target Achivement Count
target_achievement = sales_data >= sales_targets
target_count = np.sum(target_achievement)
print("Target Achievement Count:")
print(target_count)

Target Achievement Count:
13


In [ ]:
#Q51 : Best target Performng Store

target_achievement = sales_data >= sales_targets
target_count = np.sum(target_achievement, axis=1)
best_target_performing_store = np.argmax(target_count)
print("Best Target Performing Store:")
print(  stores[best_target_performing_store])
print("Target Achievement Count:")
print(target_count[best_target_performing_store])


Best Target Performing Store:
Mumbai
Target Achievement Count:
6


In [24]:
#Q52 : Target Achuvement by Category

target_achievement = sales_data >= sales_targets
target_count = np.sum(target_achievement, axis=0)
best_target_performing_category = np.argmax(target_count)
print("Best Target Performing Category:")
print(categories[best_target_performing_category])
print("Target Achievement Count:")
print(target_count[best_target_performing_category])

Best Target Performing Category:
Electronics
Target Achievement Count:
3


In [25]:
#Q53 : Sales Target Variance

variance = sales_data - sales_targets
print("Sales Target Variance:")
print(variance)

Sales Target Variance:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [26]:
#Q54 : Percentage Above or Below Target

percentage_above_below_target = np.where(sales_data >= sales_targets, "Above Target", "Below Target")
print("Percentage Above or Below Target:")
print(percentage_above_below_target)

Percentage Above or Below Target:
[['Above Target' 'Below Target' 'Below Target' 'Below Target'
  'Below Target' 'Below Target']
 ['Below Target' 'Above Target' 'Below Target' 'Above Target'
  'Above Target' 'Above Target']
 ['Above Target' 'Below Target' 'Above Target' 'Below Target'
  'Below Target' 'Below Target']
 ['Above Target' 'Above Target' 'Above Target' 'Above Target'
  'Above Target' 'Above Target']
 ['Below Target' 'Below Target' 'Below Target' 'Below Target'
  'Below Target' 'Below Target']]


In [ ]:
#q55: Stores Missing Electromics Target

electronics_target = sales_targets[0]
failed_stores = stores[sales_data[:, 0] < electronics_target]
print("Stores Missing Electronics Target:")
print(failed_stores)

Stores Missing Electronics Target:
['Hyderabad' 'Pune']


In [ ]:
#Q56 : Stores Achieving All Targets
all_targets_achieved = np.all(sales_data >= sales_targets, axis=1)
stores_achieving_all_targets = stores[all_targets_achieved]
print("Stores Achieving All Targets:")
print(stores_achieving_all_targets)

Stores Achieving All Targets:
['Mumbai']


In [27]:
#Q57 : Stores Achieving At Least One Target
at_least_one_target_achieved = np.any(sales_data >= sales_targets, axis=1)
stores_achieving_at_least_one_target = stores[at_least_one_target_achieved]
print("Stores Achieving At Least One Target:")
print(stores_achieving_at_least_one_target)

Stores Achieving At Least One Target:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


In [28]:
#Part 10 : Discount Scenario
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [29]:
#Q 58 : Discount Amount MAtrix
discount_amount = sales_data * discount_rates
print("Discount Amount Matrix:")
print(discount_amount)

Discount Amount Matrix:
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [ ]:
# 59 : Sales After Dsicount

net_sales_after_discount = sales_data - discount_amount
print("Sales After Discount:")
print(net_sales_after_discount)

Sales After Discount:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [ ]:
#60 : Profit After Discunt
profit_after_discount = net_sales_after_discount - cost_data
print("Profit After Discount:")
print(profit_after_discount)

Profit After Discount:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [ ]:
#61 : Profit MArgin After Disocunt
profit_margin_after_discount = np.round((profit_after_discount / net_sales_after_discount) * 100, 2)
print("Profit Margin After Discount (%):")
print(profit_margin_after_discount)

Profit Margin After Discount (%):
[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [ ]:
#62 : Loss Making Transcation
loss_making_transactions = np.where(profit_after_discount < 0)
print("Loss Making Transactions:")
print(loss_making_transactions)


Loss Making Transactions:
(array([], dtype=int64), array([], dtype=int64))


In [ ]:
#63 : Disocunt Impact
discount_amount = sales_data * discount_rates
total_revenue_loss = np.sum(discount_amount)
print("Total Revenue Lost Due to Discounts:", total_revenue_loss)

Total Revenue Lost Due to Discounts: 1146350.0


In [30]:
#64 : Store Most Affected by Discount

discount_amount = sales_data * discount_rates
store_discount_loss = np.sum(discount_amount, axis=1)
highest_index = np.argmax(store_discount_loss)
print("Store Most Affected by Discounts:", stores[highest_index])
print("Revenue Loss:", store_discount_loss[highest_index])

Store Most Affected by Discounts: Mumbai
Revenue Loss: 277150.0


In [31]:
#Part 11 : Tax and Price Adjustment
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [32]:
#65 : Tax Collection MAtrix
tax_collection = sales_data * tax_rates
print("Tax Collection Matrix:")
print(tax_collection)

Tax Collection Matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [ ]:
#66 : Sales Including Tax
sales_including_tax = sales_data + tax_collection
print("Sales Including Tax:")
print(sales_including_tax)


Sales Including Tax:
[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [ ]:
#67 : Store Wise Tax Collection
tax_collection = sales_data * tax_rates
store_tax_collection = np.sum(tax_collection, axis=1)
print("Store-wise Tax Collection:")
print(store_tax_collection)

Store-wise Tax Collection:
[321900. 321200. 331800. 401400. 274650.]


In [ ]:
#68 : Category Wise Tax Collection
tax_collection = sales_data * tax_rates
category_tax_collection = np.sum(tax_collection, axis=0)
print("Category-wise Tax Collection:")
print(category_tax_collection)

Category-wise Tax Collection:
[772200. 109250. 192000. 254700. 181800. 141000.]


In [ ]:
#69 : Highest Tax Contributing Store
highest_tax_index = np.argmax(np.sum(tax_collection, axis=1))
print("Highest Tax Contributing Store:", stores[highest_tax_index])
print("Total Tax Collection:", np.sum(tax_collection[highest_tax_index]))

Highest Tax Contributing Store: Mumbai
Total Tax Collection: 401400.0


In [33]:
#Part 12 : Array Modification
#70 : Updated Pune electronics sales

updated_sales = sales_data.copy()
updated_sales[4, 0] = 740000

print("Original Sales Data:")
print(sales_data)

print("\nUpdated Sales Data:")
print(updated_sales)

Original Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [34]:
#71 : Revised Beauty Cost

updated_cost = cost_data.copy()
updated_cost[:, 4] = updated_cost[:, 4] * 0.92
print("Updated Cost Data:")
print(updated_cost)

Updated Cost Data:
[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [ ]:
#72 : Furniture Cost Increase

updated_cost = cost_data.copy()
updated_cost[:, 3] = updated_cost[:, 3] * 1.12

print("Updated Cost Data:")
print(updated_cost)

Updated Cost Data:
[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [35]:
#73 : Store Closure Simulation

sales_without_pune = np.delete(sales_data, 4, axis=0)
cost_without_pune = np.delete(cost_data, 4, axis=0)

print("Sales Data Without Pune:")
print(sales_without_pune)

print("\nCost Data Without Pune:")
print(cost_without_pune)

Sales Data Without Pune:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

Cost Data Without Pune:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [ ]:
#74 : Adding a New Store
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

updated_sales = np.vstack((sales_data, delhi_sales))
updated_cost = np.vstack((cost_data, delhi_cost))
updated_stores = np.append(stores, "Delhi")

print("Updated Stores:")
print(updated_stores)

print("\nUpdated Sales Data:")
print(updated_sales)

print("\nUpdated Cost Data:")
print(updated_cost)

Updated Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]

Updated Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


In [36]:
#75 : Adding a New Product Category
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
updated_sales = np.column_stack((sales_data, home_appliance_sales))
updated_cost = np.column_stack((cost_data, home_appliance_cost))

print("Updated Sales Data:")
print(updated_sales)

print("\nUpdated Cost Data:")
print(updated_cost)

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]

Updated Cost Data:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


In [37]:
#Part 13 : Sorting and Ranking
#76 : Sort Stores by Sales
store_total_sales = np.sum(sales_data, axis=1)
sorted_indices = np.argsort(store_total_sales)
print("Stores Sorted by Total Sales:")
print(stores[sorted_indices])
print(store_total_sales[sorted_indices])

Stores Sorted by Total Sales:
['Pune' 'Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
[1980000 2270000 2295000 2310000 2820000]


In [38]:
#77 : Rank Stores by Profit
store_profit = np.sum(profit_data, axis=1)
ranked_indices = np.argsort(store_profit)[::-1]
print("Stores Ranked by Profit:")
print(stores[ranked_indices])
print(store_profit[ranked_indices])


Stores Ranked by Profit:
['Mumbai' 'Hyderabad' 'Bengaluru' 'Chennai' 'Pune']
[755000 610000 605000 600000 505000]


In [39]:
#78 : Sort Category by Revenue
category_revenue = np.sum(sales_data, axis=0)
sorted_indices = np.argsort(category_revenue)[::-1]
print("Categories Sorted by Revenue:")
print(categories[sorted_indices])
print(category_revenue[sorted_indices])

Categories Sorted by Revenue:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Sports' 'Beauty']
[4290000 2185000 1600000 1415000 1175000 1010000]


In [ ]:
#79 : Top Three Store Category Sales

flat_sales = sales_data.flatten()
top3_indices = np.argsort(flat_sales)[-3:][::-1]
rows, cols = np.unravel_index(top3_indices, sales_data.shape)

print("Top 3 Individual Sales:")

print("Sales:", flat_sales[top3_indices])
print("Stores:", stores[rows])
print("Categories:", categories[cols])

Top 3 Individual Sales:
Sales: [1050000  920000  850000]
Stores: ['Mumbai' 'Chennai' 'Bengaluru']
Categories: ['Electronics' 'Electronics' 'Electronics']


In [40]:
#80 : Bottom three profits

profit_data = sales_data - cost_data
flat_profit = profit_data.flatten()
lowest3_indices = np.argsort(flat_profit)[:3]
rows, cols = np.unravel_index(lowest3_indices, profit_data.shape)

print("Three Lowest Profit Values:")
print("Profit:", flat_profit[lowest3_indices])
print("Stores:", stores[rows])
print("Categories:", categories[cols])

Three Lowest Profit Values:
Profit: [55000 60000 60000]
Stores: ['Pune' 'Pune' 'Chennai']
Categories: ['Furniture' 'Sports' 'Sports']


In [ ]:
#Part 14 : Statistical Analysis
#81 : Sales Statistics
print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


In [41]:
#82 : Store Wise Standard Deviation
store_std = np.std(sales_data, axis=1)
print("Store-wise Standard Deviation:")
print(store_std)

Store-wise Standard Deviation:
[223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]


In [ ]:
#83 : Category Wise Standard Deviation
category_std = np.std(sales_data, axis=0)
print("Category-wise Standard Deviation:")
print(category_std)

Category-wise Standard Deviation:
[122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]


In [42]:
#84 : Sales Above company Average

average_sales = np.mean(sales_data)
above_average_count = np.sum(sales_data > average_sales)

print("Company-Wide Average Sales:", average_sales)
print("Number of Sales Values Above Average:", above_average_count)

Company-Wide Average Sales: 389166.6666666667
Number of Sales Values Above Average: 10


In [ ]:
#85 : Outier Detection

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
threshold = mean_sales + 1.5 * std_sales
high_value_outliers = sales_data[sales_data > threshold]

print("Mean Sales:", mean_sales)
print("Standard Deviation:", std_sales)
print("Outlier Threshold:", threshold)
print("High-Value Outliers:")
print(high_value_outliers)

Mean Sales: 389166.6666666667
Standard Deviation: 230322.53954448793
Outlier Threshold: 734650.4759833985
High-Value Outliers:
[ 850000  780000  920000 1050000]


In [43]:
#Part 15 : Reshaping and Transformation
#86 : Flatten Sales Data
flattened_sales = sales_data.flatten()
print("Flattened Sales Data:")
print(flattened_sales)

Flattened Sales Data:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [ ]:
#87 : Reshape Sales Data
reshaped_sales = sales_data.reshape((3,10))
print("Reshaped Sales Data:")
print(reshaped_sales)

Reshaped Sales Data:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]


In [44]:
#88 : Transpose sales data
transposed_sales = np.transpose(sales_data)
print("Transposed Sales Data:")
print(transposed_sales)

Transposed Sales Data:
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


In [45]:
#89 : Combined Sales and cost array
combined_data = np.column_stack((sales_data, cost_data))
print("Combined Sales and Cost Data:")
print(combined_data)

Combined Sales and Cost Data:
[[ 850000  420000  310000  275000  190000  225000  640000  315000  220000
   205000  125000  160000]
 [ 780000  460000  295000  310000  210000  240000  590000  350000  210000
   225000  140000  170000]
 [ 920000  390000  340000  260000  185000  215000  700000  295000  245000
   195000  120000  155000]
 [1050000  510000  375000  345000  250000  290000  790000  390000  265000
   250000  165000  205000]
 [ 690000  405000  280000  225000  175000  205000  530000  310000  205000
   170000  115000  145000]]


In [ ]:
#90 : Store Level Combined Data

data_3d = np.stack((sales_data, cost_data))

print("3D Array:")
print(data_3d)

print("\nShape of the new array:")
print(data_3d.shape)

3D Array:
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]

Shape of the new array:
(2, 5, 6)


In [46]:
#PArt 16 : Missinf data scenario
#91 : Missing value detection
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
missing_count = np.sum(np.isnan(sales_with_missing))

print("Total Missing Values:", missing_count)


rows, cols = np.where(np.isnan(sales_with_missing))

print("Row Locations:")
print(rows)

print("Column Locations:")
print(cols)

print("Stores with Missing Values:")
print(stores[rows])

print("\nCategories with Missing Values:")
print(categories[cols])

Total Missing Values: 4
Row Locations:
[0 1 3 4]
Column Locations:
[2 3 1 4]
Stores with Missing Values:
['Bengaluru' 'Hyderabad' 'Mumbai' 'Pune']

Categories with Missing Values:
['Clothing' 'Furniture' 'Groceries' 'Beauty']


In [47]:
#92 : Replace Missing Values With Zero

sales_zero = sales_with_missing.copy()
sales_zero[np.isnan(sales_zero)] = 0

print("Sales Data After Replacing Missing Values:")
print(sales_zero)

Sales Data After Replacing Missing Values:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [ ]:
#93 : Replace with comoany average
sales_average = sales_with_missing.copy()
company_average = np.nanmean(sales_with_missing)
sales_average[np.isnan(sales_average)] = company_average

print("Sales Data After Replacing Missing Values with Company Average:")
print(sales_average)

Sales Data After Replacing Missing Values with Company Average:
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [ ]:
#94 : Replace with Category Average
sales_category_average = sales_with_missing.copy()
category_averages = np.nanmean(sales_with_missing, axis=0)
sales_category_average[np.isnan(sales_category_average)] = np.take(category_averages, np.where(np.isnan(sales_category_average))[1])

print("Sales Data After Replacing Missing Values with Category Averages:")
print(sales_category_average)
print("Category Averages:")
print(category_averages)

Sales Data After Replacing Missing Values with Category Averages:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]
Category Averages:
[858000. 418750. 322500. 276250. 208750. 235000.]


In [ ]:
#95 : Missing Value IMpact

total_before = np.nansum(sales_with_missing)
total_after = np.sum(sales_zero)

print("Total Sales Before:", total_before)
print("Total Sales After:", total_after)

print("Difference:", total_before - total_after)

Total Sales Before: 10370000.0
Total Sales After: 10370000.0
Difference: 0.0


In [48]:
#Part 17 : Conditional Business Decisions
#96 : Store Performace Labels

store_total_sales = np.sum(sales_data, axis=1)
conditions = [
    store_total_sales > 2800000,
    (store_total_sales >= 2400000) & (store_total_sales <= 2800000),
    store_total_sales < 2400000
]
labels = [
    "Excellent",
    "Good",
    "Needs Improvement"
]
performance = np.select(conditions, labels, default="Unknown")

print("Stores:")
print(stores)

print("\nTotal Sales:")
print(store_total_sales)

print("\nPerformance:")
print(performance)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Total Sales:
[2270000 2295000 2310000 2820000 1980000]

Performance:
['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


In [49]:
#97 : Profitability Classifcation

profit_data = sales_data - cost_data
conditions = [
    profit_data < 0,
    (profit_data >= 0) & (profit_data < 100000),
    (profit_data >= 100000) & (profit_data <= 200000),
    profit_data > 200000
]
labels = [
    "Loss",
    "Low Profit",
    "Profitable",
    "Highly Profitable"
]
profit_class = np.select(conditions, labels, default="Unknown")

print("Profitability Classification:")
print(profit_class)

Profitability Classification:
[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [50]:
#98 : Expansion Recommendation

store_sales = np.sum(sales_data, axis=1)
profit_data = sales_data - cost_data
store_profit = np.sum(profit_data, axis=1)
store_margin = (store_profit / store_sales) * 100
eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_margin > 25)
)

eligible_stores = stores[eligible]

print("Eligible Stores:")
print(eligible_stores)

Eligible Stores:
['Mumbai']


In [51]:
#99: Category PRomotion Recommendation


profit_data = sales_data - cost_data
category_avg_sales = np.mean(sales_data, axis=0)
category_sales = np.sum(sales_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

category_profit_margin = (category_profit / category_sales) * 100
conditions = [
    (category_avg_sales < 300000) &
    (category_profit_margin > 25)
]
promotion_categories = categories[conditions[0]]

print("Categories Recommended for Additional Promotion:")
print(promotion_categories)

Categories Recommended for Additional Promotion:
['Furniture' 'Beauty' 'Sports']


In [52]:
#100 : Cost Optimization Recommendation

profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100

condition = (cost_data > 250000) & (profit_margin < 25)

rows, cols = np.where(condition)

print("Store-Category Combinations for Cost Optimization:")

print("Stores:")
print(stores[rows])

print("\nCategories:")
print(categories[cols])

print("\nCost:")
print(cost_data[rows, cols])

print("\nProfit Margin:")
print(np.round(profit_margin[rows, cols], 2))

Store-Category Combinations for Cost Optimization:
Stores:
['Bengaluru' 'Hyderabad' 'Hyderabad' 'Chennai' 'Chennai' 'Mumbai' 'Mumbai'
 'Pune' 'Pune']

Categories:
['Electronics' 'Electronics' 'Groceries' 'Electronics' 'Groceries'
 'Electronics' 'Groceries' 'Electronics' 'Groceries']

Cost:
[640000 590000 350000 700000 295000 790000 390000 530000 310000]

Profit Margin:
[24.71 24.36 23.91 23.91 24.36 24.76 23.53 23.19 23.46]


In [53]:
#Part 18 : Inventory Scenario
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
closing_stock = opening_stock - units_sold

print("Closing Stock:")
print(closing_stock)

Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [54]:
#102 : Low Stock Identification


rows, cols = np.where(closing_stock < 30)

print("Store-Category Combinations with Closing Stock Below 30:")

print("Stores:")
print(stores[rows])

print("\nCategories:")
print(categories[cols])

print("\nClosing Stock:")
print(closing_stock[rows, cols])

Store-Category Combinations with Closing Stock Below 30:
Stores:
['Bengaluru' 'Bengaluru' 'Hyderabad' 'Hyderabad' 'Chennai' 'Chennai'
 'Mumbai' 'Pune' 'Pune']

Categories:
['Electronics' 'Furniture' 'Electronics' 'Furniture' 'Electronics'
 'Furniture' 'Electronics' 'Electronics' 'Furniture']

Closing Stock:
[25 25 25 25 25 25 25 25 20]


In [ ]:
#103 : Stock Availability Percentage

closing_stock = opening_stock - units_sold
remaining_percentage = (closing_stock / opening_stock) * 100

print("Percentage of Opening Stock Remaining:")
print(np.round(remaining_percentage, 2))

Percentage of Opening Stock Remaining:
[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [ ]:
#104 : Fast Moving Products

sold_percentage = (units_sold / opening_stock) * 100
rows, cols = np.where(sold_percentage > 80)

print("Fast-Moving Store-Category Combinations:")

print("Stores:")
print(stores[rows])

print("\nCategories:")
print(categories[cols])

print("\nPercentage Sold:")
print(np.round(sold_percentage[rows, cols], 2))

Fast-Moving Store-Category Combinations:
Stores:
['Bengaluru' 'Hyderabad' 'Hyderabad' 'Chennai' 'Chennai' 'Chennai'
 'Mumbai' 'Mumbai' 'Mumbai' 'Pune']

Categories:
['Groceries' 'Groceries' 'Clothing' 'Electronics' 'Groceries' 'Clothing'
 'Electronics' 'Groceries' 'Clothing' 'Groceries']

Percentage Sold:
[84.44 84.   82.14 80.77 83.33 84.38 83.33 85.45 84.29 82.5 ]


In [ ]:
#105 : Category Wise Units Sold
#106 : Store Wise Unit SOld
store_units_sold = np.sum(units_sold, axis=1)

print("Total Units Sold by Each Store:")
print(stores)
print(store_units_sold)


category_units_sold = np.sum(units_sold, axis=0)

print("\nTotal Units Sold by Each Category:")
print(categories)
print(category_units_sold)

Total Units Sold by Each Store:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
[1110 1175 1095 1390  950]

Total Units Sold by Each Category:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']
[ 485 1950 1240  345  980  720]


In [ ]:
#107 : Best Store BY Unit Sales

best_store_index = np.argmax(store_units_sold)
best_store = stores[best_store_index]

print("Best-Selling Store:")
print(best_store)
print("Total Units Sold:", store_units_sold[best_store_index])

Best-Selling Store:
Mumbai
Total Units Sold: 1390


In [ ]:
#108 : Reorder requirment

reorder_matrix = closing_stock < 25

print("Reorder Matrix:")
print(reorder_matrix)

Reorder Matrix:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [55]:
#109 : Reorder Quanitiy
# Reorder quantity
reorder_quantity = np.where(closing_stock < 25,100 - closing_stock, 0)

print("Reorder Quantity:")
print(reorder_quantity)

Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


In [56]:
#Part19 : Advanced Numpy Questions
#Q110 : Cumulative Store Sales
cumulative_sales = np.cumsum(sales_data, axis=1)

print("Cumulative Sales:")
print(cumulative_sales)

Cumulative Sales:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [57]:
#Q111 : Cumulative Company Sales
company_cumulative_sales = np.cumsum(sales_data)

print("Cumulative Company Sales:")
print(company_cumulative_sales)

Cumulative Company Sales:
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [58]:
#Q112 : Sales Difference Between Categories
category_sales_diff = np.diff(sales_data, axis=0)

print("Sales Difference Between Categories:")
print(category_sales_diff)


Sales Difference Between Categories:
[[ -70000   40000  -15000   35000   20000   15000]
 [ 140000  -70000   45000  -50000  -25000  -25000]
 [ 130000  120000   35000   85000   65000   75000]
 [-360000 -105000  -95000 -120000  -75000  -85000]]


In [59]:
#Q113 : Unique Sales Vaules
unique_sales = np.unique(sales_data)

print("Unique Sales Values:")
print(unique_sales)

Unique Sales Values:
[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]


In [60]:
#Q114 : Search for specific Sales
rows, cols = np.where(sales_data == 420000)
print("Rows:", rows)
print("Columns:", cols)
print("\nStore:", stores[rows])
print("Category:", categories[cols])

Rows: [0]
Columns: [1]

Store: ['Bengaluru']
Category: ['Groceries']


In [61]:
#Q115 : Compare Sales and Cost

profitable = sales_data > cost_data
print("Sales > Cost:")
print(profitable)
all_profitable = np.all(profitable)

print("\nAre all combinations profitable?")
print(all_profitable)

Sales > Cost:
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]

Are all combinations profitable?
True


In [62]:
#Q116 : Clip Profit Values
profit_data = sales_data - cost_data
reporting_profit = np.clip(profit_data, 75000, 250000)

print("Reporting Profit Array:")
print(reporting_profit)

Reporting Profit Array:
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [63]:
#Q117 : Normalize Sales Data
normalized_sales = (sales_data - np.min(sales_data)) / (np.max(sales_data) - np.min(sales_data))

print("Normalized Sales Data:")
print(normalized_sales)

Normalized Sales Data:
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [64]:
#118 : Standardize Sales Data
standardized_sales = (sales_data - np.mean(sales_data)) / np.std(sales_data)

print("Standardized Sales Data:")
print(standardized_sales)

Standardized Sales Data:
[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [65]:
#119 : ROund Values
rounded_sales = np.round(sales_data, 2)

print("Rounded Sales Data:")
print(rounded_sales)

Rounded Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [66]:
#120 : Save and Load Data
profit_data = sales_data - cost_data
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)
loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

print("Sales arrays equal:", np.array_equal(sales_data, loaded_sales))
print("Cost arrays equal:", np.array_equal(cost_data, loaded_cost))
print("Profit arrays equal:", np.array_equal(profit_data, loaded_profit))

Sales arrays equal: True
Cost arrays equal: True
Profit arrays equal: True


In [79]:
# ==========================================
# SMARTMART RETAIL PERFORMANCE REPORT
# ==========================================

profit_data = sales_data - cost_data

# ==========================================
# COMPANY SUMMARY
# ==========================================

total_sales = np.sum(sales_data)
total_cost = np.sum(cost_data)
total_profit = np.sum(profit_data)

overall_profit_margin = (total_profit / total_sales) * 100

average_transaction_value = np.mean(sales_data)
highest_sales = np.max(sales_data)
lowest_sales = np.min(sales_data)


# ==========================================
# STORE SUMMARY
# ==========================================

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

store_profit_margin = (store_profit / store_sales) * 100

sales_targets = np.array([
    800000, 450000, 320000,
    300000, 200000, 230000
])

target_matrix = sales_data >= sales_targets

store_target_count = np.sum(target_matrix, axis=1)


store_units_sold = np.sum(units_sold, axis=1)


expansion = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_profit_margin > 25)
)


# ==========================================
# CATEGORY SUMMARY
# ==========================================

category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

category_profit_margin = (
    category_profit / category_sales
) * 100

category_average_sales = np.mean(sales_data, axis=0)

category_target_count = np.sum(target_matrix, axis=0)

category_units_sold = np.sum(units_sold, axis=0)


# ==========================================
# MANAGEMENT RECOMMENDATIONS
# ==========================================


best_store_index = np.argmax(store_profit)

lowest_store_index = np.argmin(store_profit)

best_category_index = np.argmax(category_profit)

lowest_category_index = np.argmin(category_profit)


# ==========================================
# ADDITIONAL MARKETING
# ==========================================

marketing_condition = (
    (category_average_sales < 300000) &
    (category_profit_margin > 25)
)

marketing_categories = categories[marketing_condition]


# ==========================================
# COST OPTIMIZATION
# ==========================================

cost_optimization = (
    (cost_data > 250000) &
    (profit_data / sales_data * 100 < 25)
)

cost_rows, cost_cols = np.where(cost_optimization)


# ==========================================
# INVENTORY REORDER
# ==========================================

closing_stock = opening_stock - units_sold

reorder_condition = closing_stock < 25

reorder_quantity = np.where(
    reorder_condition,
    100 - closing_stock,
    0
)

reorder_rows, reorder_cols = np.where(reorder_condition)


# ==========================================
# FINAL REPORT
# ==========================================

print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")

print("\nCOMPANY SUMMARY")
print("---------------")
print("Total Sales:", total_sales)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print("Overall Profit Margin:",
      round(overall_profit_margin, 2), "%")


print("\nBEST-PERFORMING STORE")
print("---------------------")

print("Store:", stores[best_store_index])
print("Sales:", store_sales[best_store_index])
print("Cost:", store_cost[best_store_index])
print("Profit:", store_profit[best_store_index])
print("Profit Margin:",
      round(store_profit_margin[best_store_index], 2), "%")


print("\nMOST PROFITABLE CATEGORY")
print("------------------------")

print("Category:", categories[best_category_index])
print("Sales:", category_sales[best_category_index])
print("Cost:", category_cost[best_category_index])
print("Profit:", category_profit[best_category_index])
print("Profit Margin:",
      round(category_profit_margin[best_category_index], 2), "%")


print("\nEXPANSION RECOMMENDATIONS")
print("-------------------------")
print("Eligible Stores:", stores[expansion])


print("\nCOST OPTIMIZATION")
print("-----------------")

print("Store:", stores[cost_rows])
print("Category:", categories[cost_cols])
print("Cost:", cost_data[cost_rows, cost_cols])
print(
    "Profit Margin:",
    np.round(
        (profit_data[cost_rows, cost_cols] /
         sales_data[cost_rows, cost_cols]) * 100,
        2
    )
)


print("\nINVENTORY REORDER")
print("-----------------")

print("Store:", stores[reorder_rows])
print("Category:", categories[reorder_cols])
print("Closing Stock:",
      closing_stock[reorder_rows, reorder_cols])
print("Reorder Quantity:",
      reorder_quantity[reorder_rows, reorder_cols])

SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34 %

BEST-PERFORMING STORE
---------------------
Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000
Profit Margin: 26.77 %

MOST PROFITABLE CATEGORY
------------------------
Category: Electronics
Sales: 4290000
Cost: 3250000
Profit: 1040000
Profit Margin: 24.24 %

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores: ['Mumbai']

COST OPTIMIZATION
-----------------
Store: ['Bengaluru' 'Hyderabad' 'Hyderabad' 'Chennai' 'Chennai' 'Mumbai' 'Mumbai'
 'Pune' 'Pune']
Category: ['Electronics' 'Electronics' 'Groceries' 'Electronics' 'Groceries'
 'Electronics' 'Groceries' 'Electronics' 'Groceries']
Cost: [640000 590000 350000 700000 295000 790000 390000 530000 310000]
Profit Margin: [24.71 24.36 23.91 23.91 24.36 24.76 23.53 23.19 23.46]

INVENTORY REORDER
-----------------
Store: ['Pune']
Category: ['Furniture']
Clo